### ISSUE TITLE
Texture/Setting

### ISSUE THREAD

**Issue by JamesVo1** [soft-eng-practicum/ForkKnightGame#16] opened 2014-04-12 05:47 UTC
Jump high enough, the map ends and a grey area is seen.

Fix: adjust camera to a maximum height of the map.

**Comment by notagainjen** [comment] 2014-04-12 11:41
Hey James, I was able to reproduce this. I'm just adding more detail to this issue for just for the sake of testing, 

Steps to reproduce:
1. Launch forkknightthegame.com
2. Move left or right until you are blocked by one of the barns
3. Tap the Up Key (Jump) several times

Observed: A horizontal grey line appears directly above the barn. This line seems to serve as an indicator of the top of the barn.

Expected: Perry shouldn't be able to jump that high off-screen as noted in issue #1 . Grey line/indicator shouldn't appear above barn.

Notes:
Screenshot Attached.
Reproduction Rate: 5/5
![greylinebarn_fk](https://cloud.githubusercontent.com/assets/6340830/2687138/9cc317cc-c237-11e3-85ca-8baa2cfdbaaf.png)

**Comment by lyche9** [comment] 2014-04-12 13:34
This is also a result of the background sprite not being large enough. (You can clearly see this in unity by dragging a background texture into scene view.) In addition to adding a max height, the final background sprite should be taller than 1200px.

The grey background is the default color background, what you would see if there was no background sprite.

The grey line over the barn is because the barn sprite was grabbed off of Google images and in the rush I didn't have time to crop it correctly. :)

Should we be listing issues that involve the place holder sprites? Background picture too short, images that won't be in the game not being cropped correctly...?

**Comment by lyche9** [comment] 2014-04-12 14:33
If it's okay, I'm removing the bug tag on this issue. The code here is working exactly as intended.

**Comment by notagainjen** [comment] 2014-04-12 19:47
I understand that those are placeholder images, but the grey line doesn't just occur on the barn, it also occurs above Perry's head throughout gameplay.

**Comment by lyche9** [comment] 2014-04-12 23:53
It's fixed by slicing the sprite in sprite renderer. Probably needs to be reimported.

**Comment by lyche9** [comment] 2014-04-25 07:31
Jump disabled. Sprite/texture settings set to "Point".

**Closed as completed by lyche9** 2014-04-25 07:31 UTC
Labels: wontfix, infinite jump
